name: CustomEnchants
main: yournamespace\yourplugin\Main
version: 1.0.0
api: [5.0.0] # Adjust API version if needed for your PMMP installation
author: YourName
description: Adds custom enchantments to the server.

commands:
  customenchant:
    description: Apply a custom enchantment to the item in hand.
    usage: "/customenchant <enchantName> <level> [player]"
    permission: customenchants.command.use

permissions:
  customenchants.command.use:
    description: Allows using the /customenchant command.
    default: op
